// Tracked stand-in for the reference Expo writes into `expo-env.d.ts`.
//
// `expo-env.d.ts` is generated by the Expo CLI on `expo start` / `prebuild`
// and is git-ignored (see .gitignore) because the CLI owns it and rewrites it.
// That is correct on a developer machine, where the CLI has already run — but
// CI never starts Expo, so the file simply does not exist there and
// `import '../global.css'` in app/_layout.tsx had no declaration:
//
//   app/_layout.tsx(1,8): error TS2882: Cannot find module or type
//   declarations for side-effect import of '../global.css'.
//
// which failed the mobile typecheck job on every push. `expo/types` is what
// declares the CSS side-effect module, so referencing it from a tracked file
// makes the typecheck self-contained. A triple-slash reference is idempotent:
// when the generated file is present too, TypeScript resolves `expo/types`
// once and the two agree.
/// <reference types="expo/types" />
